# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# ===================================================================

# ===================================================================
# Application properties
# ===================================================================
#application:


# ===================================================================
# Spring properties
# ===================================================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/generic_controller_demo?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678

  # JPA configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
        format_sql: true
        type: trace
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: validate
    show-sql: on

# ===================================================================
# Logger
# ===================================================================
logging:
  level:
    root: INFO
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
server:
  port: 9090
